#!/bin/bash
#
# interactive git status menu
# allow staging ustaging actions
#
# @params
# Globals
#   None
# Arguments
#   None

set -e
set -f

mydir="${0%/*}"
source "${mydir}"/../helper/set_variable.sh
source "${mydir}"/../helper/git_query.sh

function usage() {
  echo -e "Usage: dotbare fstat [-h] ...\n"
  echo -e "Display interactive git status menu"
  echo -e "Stage, unstage, edit file interactively\n"
  echo -e "optional arguments:"
  echo -e "  -h\t\tshow this help message and exit"
}

while true; do
  selected_files=$(get_modified_file | tr '\n' ' ')
  [[ -z "${selected_files}" ]] && break
  set +e
  # shellcheck disable=SC2086
  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" diff-index --cached --quiet HEAD ${selected_files}
  if [[ "$?" -eq 0 ]]; then
    # shellcheck disable=SC2086
    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" add ${selected_files}
  else
    # shellcheck disable=SC2086
    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" reset --quiet HEAD ${selected_files}
  fi
  set -e
done
