#!/bin/bash
#
# stash operation using fzf
#
# @params
# Globals
#   ${mydir}: current dir of the script, source purpose
#   ${stash_file}: select modified files and stash
#   ${selected_file}: selected files to stash
#   ${selected_stash}: selected stash to apply
# Arguments
#   None

set -e
set -f

mydir="${0%/*}"
source "${mydir}"/../helper/set_variable.sh
source "${mydir}"/../helper/get_confirmation.sh
source "${mydir}"/../helper/git_query.sh

function usage() {
  echo -e "Usage: dotbare fstash [-h] [-a] [-b] [-c] ...\n"
  echo -e "save/apply stash using fzf"
  echo -e "By default, running fstash will apply the selected stash"
  echo -e "To stash only some files, add -f flag\n"
  echo -e "optional arguments:"
  echo -e "  -h\tshow this help message and exit"
  echo -e "  -f\tselect modified files through fzf and stash them"
}

stash_file=""

while getopts ":hf" opt; do
  case "$opt" in
    f)
      stash_file='true'
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      echo "Invalid option: ${OPTARG}" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -n "${stash_file}" ]]; then
  selected_files=$(get_modified_file "select files to add to a stash")
  [[ -z "${selected_files}" ]] && exit 1
  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" stash -- ${selected_files}
else
  selected_stash=$(get_stash "select stash to apply")
  [[ -z "${selected_stash}" ]] && exit 1
  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" stash apply "${selected_stash}"
fi
